routes/web.php
<?php

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');


////////////////////////////// ADMIN AREA //////////////////////////////

Route::prefix('/admin')->middleware('auth')->group(function () {

    Route::get('/', function () {
            return redirect()->route('dashboard.index');
    })->name('admin.index');

    Route::view('/dashboard', 'backend.dashboard.index')->name('dashboard.index');

    Route::resource('/category', 'CategoryController');
    Route::resource('/tag', 'TagController');
    Route::resource('/post', 'PostController');
    Route::resource('/like', 'LikeController');
    
    Route::resource('/user', 'UserController');
    
});


////////////////////////////// FRONT-END //////////////////////////////

Route::get('/', 'MainController@home');
Route::get('/how-it-works', 'MainController@how_it_works');
Route::get('/sellers', 'MainController@sellers');
Route::get('/dealers', 'MainController@dealers');
Route::get('/blog', 'MainController@blog');
Route::get('/blog/post/{id}', 'MainController@article')->name('blog.article');
Route::get('/about-us', 'MainController@about_us');
Route::get('/contact-us', 'MainController@contact_us');
Route::get('/download-app', 'MainController@download_app');
Route::get('/faq', 'MainController@faq');
Route::get('/tips', 'MainController@tips');

Route::get('/tag/{tag}', 'MainController@blogsByTag')->name('blogs.by-tag');
Route::get('/category/{category}', 'MainController@blogsByCategory')->name('blogs.by-category');

Route::resource('post-like', 'PostLikeController', ['parameters' => ['post-like' => 'post']]);

//
Route::any('/assets/img/{slug}', function(){
    return \Image::canvas(800, 600, '#ff0000')->response('jpg');
});

app/models/Post.php
<?php

namespace App\Models;

use App\User;
use App\Traits\UuidKey;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use UuidKey;
    use SoftDeletes;

    protected $hidden = ['id'];

    protected $fillable = [
        'user_id',
        'title',
        'excerpt',
        'body',
        'meta_description',
        'published_at',
        'previewed_at'
    ];

    protected $dates = [
        'deleted_at',
        'published_at',
        'previewed_at'
    ];


    /*************************************** RELATIONSHIP ****************************************/

    /**
     * One-to-Many: A user may create zero or many post
     *
     * This function will retrieve the creator (user) of a post.
     * See: User' posts() method for the inverse
     *
     * @return mixed
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Many-to-Many: A post may have one or many categories.
     *
     * This function will retrieve the categories of a post.
     * See: Category's posts() method for the inverse
     *
     * @return mixed
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class)
                    ->withTrashed();
    }

    /**
     * Many-to-Many Polymorphic: A post may have one or many tags.
     *
     * This function will retrieve the tags of a post.
     * See: Tag's posts() method for the inverse
     *
     * @return mixed
     */
    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable');
    }

    /**
     * Polymorphic: A product may have one or more images.
     *
     * This function will retrieve the images of a product.
     * See: Image's imageable() method
     *
     * @return mixed
     */
    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    /**
     * One-to-One: A post may have zero or one social SEO
     *
     * This function will retrieve the social SEO of a post
     * See: Social' post() method for the inverse
     *
     * @return mixed
     */
    public function social()
    {
        return $this->hasOne(Social::class);
    }

    /**
     * One-to-Many: A post may have zero or many likes
     *
     * This function will retrieve the likes of a post
     * See: Like' post() method for the inverse
     *
     * @return mixed
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }


    /***************************************** ACCESSOR ******************************************/

    public function getPublishedAtFormattedAttribute()
    {
        return ($this->published_at) ? 
                    '<strong class="text-green">YES</strong> <br>' .
                    '<span class="text-muted">' . 
                        $this->published_at->format('d-M-Y') . 
                    '<span>' : 
                    '<strong class="text-red">NO</strong>';
    }

    public function getCreatedAtFormattedAttribute()
    {
        return $this->created_at->diffForHumans() . '<br>' .
                '<small class="text-muted">' .
                    $this->created_at->format('d-M-Y') .
                '</small>';
    }

    public function getCategoryListAttribute()
    {
        if ($this->categories->isEmpty()) return '-';

        foreach ($this->categories as $category) {
            echo '<a href="#">' . $category->name . '</a>, ';
        }
    }

    public function getTagListAttribute()
    {
        if ($this->tags->isEmpty()) return '-';
        
        foreach ($this->tags as $tag) {
            echo '<a href="#">' . $tag->name . '</a>, ';
        }
    }

    public function getFeaturedImageAttribute()
    {
        return $this->images()->latest()->first();
    }


    /***************************************** HELPER ********************************************/

    public function toggleLike($user = null) {
        
        if ($user == null) {

            $ip = $_SERVER['REMOTE_ADDR'] ?: 
                    ($_SERVER['HTTP_X_FORWARDED_FOR'] ?: $_SERVER['HTTP_CLIENT_IP']);

            $this->likes()->updateOrCreate(['ip_address' => $ip]);

        } 
        else {
            
            $this->likes()->updateOrCreate(['user_id' => $user->id]);
        }
    }
}

resources/views/pages/article.blade.php
@extends('layouts._blog')

@push('page-meta')
	<title>{{ $post->title }} - The Open Road - 123Quanto Blog</title>
@endpush

@push('body-class')
	<body id="blog-page">
@endpush

@section('content')
	<section class="blog-article">
		<div class="grid-container">
			<div class="grid-x grid-padding-x align-center">
				<div class="cell large-12">
					<div class="grid-x grid-padding-x">
						<div class="cell large-9">
							<div class="grid-x grid-padding-x">
								<div class="cell large-12 item large">
									@if ($post->featured_image)
										<img src="{{ asset('storage/' . $post->featured_image->path) }}">
									@endif
									
									<h2>{{ $post->title }}</h2>
									
									<div class="hide author">
										<div class="avatar">
											<img src="{{ asset('assets/img/avatar.jpg') }}">
										</div>
										
										<p>{{ $post->user->name }}</p>
									</div>
									
									<div class="statistic">
										@include('common.blog.love', ['data' => $post])
										
										<p class="share">
											@component('common.buttons.share.facebook')
												@slot('data', $post)
											@endcomponent

											@component('common.buttons.share.twitter')
												@slot('post', $post)
											@endcomponent

											@component('common.buttons.share.linkedin')
												@slot('post', $post)
											@endcomponent
										</p>
									</div>
									
									{!! $post->body !!}
									
									<div class="statistic">
										@include('common.blog.love', ['data' => $post])
										
										<p class="share">
											@component('common.buttons.share.facebook')
												@slot('data', $post)
											@endcomponent

											@component('common.buttons.share.twitter')
												@slot('post', $post)
											@endcomponent

											@component('common.buttons.share.linkedin')
												@slot('post', $post)
											@endcomponent
										</p>
									</div>
								</div>
							</div>
							<hr>
						</div>
						
						<aside class="blog cell large-3 hide-for-xsmall-only hide-for-small-only">
							@include('layouts.blog-aside', ['tags' => $tags, 'categories' => $categories])
						</aside>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="blog-list">
		<div class="grid-container">
			<div class="grid-x grid-padding-x">
				<div class="cell large-12">
					<h3>More from our blog</h3>
					
					<div class="grid-x grid-padding-x large-up-4">
						@foreach ($more_posts as $post)
							<div class="cell item small">
								@if ($post->featured_image)
									<img src="{{ asset(imageFly('storage/' . $post->featured_image->path, [400, 150])) }}" width="100%" alt="{{ $post->title }}">
								@endif
								
								<p class="title">
									<a href="{{ route('blog.article', $post) }}">
										{{ $post->title }}
									</a>
								</p>
								
								<p>{{ $post->excerpt }}</p>
								
								<footer>
									@include('common.blog.love', ['data' => $post])
									
									<p class="share">
										@component('common.buttons.share.facebook')
											@slot('data', $post)
										@endcomponent

										@component('common.buttons.share.twitter')
											@slot('post', $post)
										@endcomponent
									</p>
								</footer>
							</div>
						@endforeach
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection


@push('page-meta')
	@include('common.meta.facebook', ['post' => $post ?? null])
@endpush

@push('body-scripts')
	{{--  Load Facebook SDK for JavaScript  --}}
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12&appId=1946661455653025&autoLogAppEvents=1';
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
@endpush

@push('page-scripts')
	<script>window.twttr = (function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0],
		t = window.twttr || {};
	if (d.getElementById(id)) return t;
	js = d.createElement(s);
	js.id = id;
	js.src = "https://platform.twitter.com/widgets.js";
	fjs.parentNode.insertBefore(js, fjs);

	t._e = [];
	t.ready = function(f) {
		t._e.push(f);
	};

	return t;
	}(document, "script", "twitter-wjs"));</script>
@endpush

resources/views/pages/blog-by-category.blade.php
@extends('layouts._blog')

@push('page-meta')
	<title>The Open Road - 123Quanto Blog</title>
@endpush

@push('body-class')
	<body id="blog-page">
@endpush

@section('content')
	<section class="hero-image grid-x" data-interchange="[assets/img/background-hero-image-home-large.jpg, xsmall], [assets/img/background-hero-image-home-large.jpg, small], [assets/img/background-hero-image-home-large.jpg, medium], [assets/img/background-hero-image-home-large.jpg, large]">
		<div class="cell text-center">
			<h1>The Open Road</h1>

			<p>Articles for sellers, dealers and auto enthusiasts</p>
		</div>
	</section>

	<section class="blog-list">
		<div class="grid-container">
			<h2 style="font-size: 24px;">Posts by Category: {{ $category->name }}</h2>
			<div class="grid-x grid-padding-x">
				<div class="cell xsmall-12 large-9">
					
					@if ($posts->isEmpty())
						@component('common.datalist.no-data')
							@slot('text', 'No article for this category')
							@slot('border_style', 'margin-top: 40px;')
							@slot('text_style', 'padding-top: 15px;')
						@endcomponent
					@else
						@foreach ($posts->chunk(3) as $chunked_posts)
							<div data-equalizer="excerpt">
								<div class="grid-x grid-padding-x xsmall-up-1 medium-up-2 large-up-3 blog-items" 
									id="blog-items-{{ ($loop->iteration + 1) }}" data-equalizer="title">
									@foreach ($chunked_posts as $post)
										<div class="cell item small">
											@if ($post->featured_image)
												<img src="{{ asset(imageFly('storage/' . $post->featured_image->path, [400, 150])) }}" width="100%" alt="{{ $post->title }}">
											@endif

											<p class="title" data-equalizer-watch="title">
												<a href="{{ route('blog.article', $post) }}">
													{{ $post->title }}
												</a>
											</p>
											
											<p data-equalizer-watch="excerpt">{{ $post->excerpt }}</p>
											
											<footer>
												<p><i class="fa fa-heart fa-lg"></i> 2000</p>

												<p class="share">
													@component('common.buttons.share.facebook')
														@slot('data', $post)
													@endcomponent

													@component('common.buttons.share.twitter')
														@slot('post', $post)
													@endcomponent

													@component('common.buttons.share.linkedin')
														@slot('post', $post)
													@endcomponent
												</p>
											</footer>
										</div>
									@endforeach
								</div>
							</div>
						@endforeach
					@endif
					
					<div class="grid-x grid-padding-x">
						<div class="cell text-center">
							{{ $posts->links('common.pagination.blog') }}
						</div>
					</div>
				</div>
				
				<aside class="blog cell large-3 hide-for-xsmall-only hide-for-small-only hide-for-medium-only">
					@include('layouts.blog-aside', ['tags' => $tags, 'categories' => $categories])
				</aside>
			</div>
		</div>
	</section>
@endsection


@push('page-meta')
	@include('common.meta.facebook', ['post' => $post ?? null])
@endpush

@push('body-scripts')
	{{--  Load Facebook SDK for JavaScript  --}}
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12&appId=1946661455653025&autoLogAppEvents=1';
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
@endpush

@push('page-scripts')
	<script>window.twttr = (function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0],
		t = window.twttr || {};
	if (d.getElementById(id)) return t;
	js = d.createElement(s);
	js.id = id;
	js.src = "https://platform.twitter.com/widgets.js";
	fjs.parentNode.insertBefore(js, fjs);

	t._e = [];
	t.ready = function(f) {
		t._e.push(f);
	};

	return t;
	}(document, "script", "twitter-wjs"));</script>
@endpush

@push('page-scripts')
<script>
var counter = 0;

$('.blog-items').each(function()
{
	var element = $(this).attr('id');
	
	var item_counter = 0;
	$(this).find('.item').each(function()
	{
		$(this).prop('style', 'transition-delay:'+ (item_counter * 0.125)  + 's');
		item_counter++;
	});
	
	var controller = new ScrollMagic.Controller();
	
	var scene = new ScrollMagic.Scene({
		triggerElement: "#" + element,
		//triggerHook: "onEnter",
		duration: "100%"
		
	})
	//.addIndicators()
	.on("enter", function(){
		$("#" + element).addClass('is-in-view');
	})
	.addTo(controller);
	
	counter++;
	
});
</script>
@endpush

resources/views/pages/blog-by-tag.blade.php
@extends('layouts._blog')

@push('page-meta')
	<title>The Open Road - 123Quanto Blog</title>
@endpush

@push('body-class')
	<body id="blog-page">
@endpush

@section('content')
	<section class="hero-image grid-x" data-interchange="[assets/img/background-hero-image-home-large.jpg, xsmall], [assets/img/background-hero-image-home-large.jpg, small], [assets/img/background-hero-image-home-large.jpg, medium], [assets/img/background-hero-image-home-large.jpg, large]">
		<div class="cell text-center">
			<h1>The Open Road</h1>

			<p>Articles for sellers, dealers and auto enthusiasts</p>
		</div>
	</section>

	<section class="blog-list">
		<div class="grid-container">
			<h2 style="font-size: 24px;">Posts by Tag: {{ $tag->name }}</h2>
			<div class="grid-x grid-padding-x">
				<div class="cell xsmall-12 large-9">
					
					@if ($posts->isEmpty())
						@component('common.datalist.no-data')
							@slot('text', 'No article for this tag')
							@slot('border_style', 'margin-top: 40px;')
							@slot('text_style', 'padding-top: 15px;')
						@endcomponent
					@else
						@foreach ($posts->chunk(3) as $chunked_posts)
							<div data-equalizer="excerpt">
								<div class="grid-x grid-padding-x xsmall-up-1 medium-up-2 large-up-3 blog-items" 
									id="blog-items-{{ ($loop->iteration + 1) }}" data-equalizer="title">
									@foreach ($chunked_posts as $post)
										<div class="cell item small">
											@if ($post->featured_image)
												<img src="{{ asset(imageFly('storage/' . $post->featured_image->path, [400, 150])) }}" width="100%" alt="{{ $post->title }}">
											@endif

											<p class="title" data-equalizer-watch="title">
												<a href="{{ route('blog.article', $post) }}">
													{{ $post->title }}
												</a>
											</p>
											
											<p data-equalizer-watch="excerpt">{{ $post->excerpt }}</p>
											
											<footer>
												<p><i class="fa fa-heart fa-lg"></i> 2000</p>

												<p class="share">
													@component('common.buttons.share.facebook')
														@slot('data', $post)
													@endcomponent

													@component('common.buttons.share.twitter')
														@slot('post', $post)
													@endcomponent

													@component('common.buttons.share.linkedin')
														@slot('post', $post)
													@endcomponent
												</p>
											</footer>
										</div>
									@endforeach
								</div>
							</div>
						@endforeach
					@endif
					
					<div class="grid-x grid-padding-x">
						<div class="cell text-center">
							{{ $posts->links('common.pagination.blog') }}
						</div>
					</div>
				</div>
				
				<aside class="blog cell large-3 hide-for-xsmall-only hide-for-small-only hide-for-medium-only">
					@include('layouts.blog-aside', ['tags' => $tags, 'categories' => $categories])
				</aside>
			</div>
		</div>
	</section>
@endsection


@push('page-meta')
	@include('common.meta.facebook', ['post' => $post ?? null])
@endpush

@push('body-scripts')
	{{--  Load Facebook SDK for JavaScript  --}}
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12&appId=1946661455653025&autoLogAppEvents=1';
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
@endpush

@push('page-scripts')
	<script>window.twttr = (function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0],
		t = window.twttr || {};
	if (d.getElementById(id)) return t;
	js = d.createElement(s);
	js.id = id;
	js.src = "https://platform.twitter.com/widgets.js";
	fjs.parentNode.insertBefore(js, fjs);

	t._e = [];
	t.ready = function(f) {
		t._e.push(f);
	};

	return t;
	}(document, "script", "twitter-wjs"));</script>
@endpush

@push('page-scripts')
<script>
var counter = 0;

$('.blog-items').each(function()
{
	var element = $(this).attr('id');
	
	var item_counter = 0;
	$(this).find('.item').each(function()
	{
		$(this).prop('style', 'transition-delay:'+ (item_counter * 0.125)  + 's');
		item_counter++;
	});
	
	var controller = new ScrollMagic.Controller();
	
	var scene = new ScrollMagic.Scene({
		triggerElement: "#" + element,
		//triggerHook: "onEnter",
		duration: "100%"
		
	})
	//.addIndicators()
	.on("enter", function(){
		$("#" + element).addClass('is-in-view');
	})
	.addTo(controller);
	
	counter++;
	
});
</script>
@endpush

resources/views/pages/blog.blade.php
@extends('layouts._blog')

@push('page-meta')
	<title>The Open Road - 123Quanto Blog</title>
@endpush

@push('body-class')
	<body id="blog-page">
@endpush

@section('content')
	<section class="hero-image grid-x" data-interchange="[assets/img/background-hero-image-home-large.jpg, xsmall], [assets/img/background-hero-image-home-large.jpg, small], [assets/img/background-hero-image-home-large.jpg, medium], [assets/img/background-hero-image-home-large.jpg, large]">
		<div class="cell text-center">
			<h1>The Open Road</h1>

			<p>Articles for sellers, dealers and auto enthusiasts</p>
		</div>
	</section>

	@if (isset($latest_post) && isset($remaining_posts))
		<section class="blog-list">
			<div class="grid-container">
				<div class="grid-x grid-padding-x">
					<div class="cell xsmall-12 large-9">

						<div class="grid-x grid-padding-x blog-items" id="blog-items-1">
							<div class="cell large-12 item large">
								@if ($latest_post->featured_image)
									<img src="{{ asset(imageFly('storage/' . $latest_post->featured_image->path, [870, 327])) }}" width="100%" alt="{{ $latest_post->title }}">
								@endif
								<div class="container">
									<div class="box">
										<p class="title">
											<a href="{{ route('blog.article', $latest_post) }}">
												
											</a>
										</p>
										
										<p>{{ $latest_post->excerpt }}</p>
										
										<footer>
											@include('common.blog.love', ['data' => $latest_post])

											<p class="share">
												@component('common.buttons.share.facebook')
													@slot('data', $latest_post)
												@endcomponent

												@component('common.buttons.share.twitter')
													@slot('post', $latest_post)
												@endcomponent

												@component('common.buttons.share.linkedin')
													@slot('post', $latest_post)
												@endcomponent
											</p>
										</footer>
									</div>
								</div>
							</div>
						</div>	
						
						@foreach ($remaining_posts->chunk(3) as $chunked_remaining_posts)
							<div data-equalizer="excerpt">
								<div class="grid-x grid-padding-x xsmall-up-1 medium-up-2 large-up-3 blog-items" 
									id="blog-items-{{ ($loop->iteration + 1) }}" data-equalizer="title">
									@foreach ($chunked_remaining_posts as $post)
										<div class="cell item small">
											@if ($post->featured_image)
												<img src="{{ asset(imageFly('storage/' . $post->featured_image->path, [400, 150])) }}" width="100%" alt="{{ $post->title }}">
											@endif
											
											<p class="title" data-equalizer-watch="title">
												<a href="{{ route('blog.article', $post) }}">
													{{ $post->title }}
												</a>
											</p>
											
											<p data-equalizer-watch="excerpt">{{ $post->excerpt }}</p>

											<footer>
												@include('common.blog.love', ['data' => $post])

												<p class="share">
													@component('common.buttons.share.facebook')
														@slot('data', $post)
													@endcomponent
		
													@component('common.buttons.share.twitter')
														@slot('post', $post)
													@endcomponent

													@component('common.buttons.share.linkedin')
														@slot('post', $post)
													@endcomponent
												</p>
											</footer>
										</div>
									@endforeach
								</div>
							</div>
						@endforeach
						
						<div class="grid-x grid-padding-x">
							<div class="cell text-center">
								{{ $remaining_posts->links('common.pagination.blog') }}
							</div>
						</div>
					</div>
					
					<aside class="blog cell large-3 hide-for-xsmall-only hide-for-small-only hide-for-medium-only">
						@include('layouts.blog-aside', ['tags' => $tags, 'categories' => $categories])
					</aside>
				</div>
			</div>
		</section>
    @endif
@endsection


@push('page-meta')
	@include('common.meta.facebook', ['post' => $post ?? null])
@endpush

@push('body-scripts')
	{{--  Load Facebook SDK for JavaScript  --}}
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12&appId=1946661455653025&autoLogAppEvents=1';
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
@endpush

@push('page-scripts')
<script>
	var counter = 0;

	$('.blog-items').each(function()
	{
		var element = $(this).attr('id');
		
		var item_counter = 0;
		$(this).find('.item').each(function()
		{
			$(this).prop('style', 'transition-delay:'+ (item_counter * 0.125)  + 's');
			item_counter++;
		});
		
		var controller = new ScrollMagic.Controller();
		
		var scene = new ScrollMagic.Scene({
			triggerElement: "#" + element,
			//triggerHook: "onEnter",
			duration: "100%"
			
		})
		//.addIndicators()
		.on("enter", function(){
			$("#" + element).addClass('is-in-view');
		})
		.addTo(controller);
		
		counter++;
		
	});
</script>
@endpush

@push('page-scripts')
	<script>window.twttr = (function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0],
		t = window.twttr || {};
	if (d.getElementById(id)) return t;
	js = d.createElement(s);
	js.id = id;
	js.src = "https://platform.twitter.com/widgets.js";
	fjs.parentNode.insertBefore(js, fjs);

	t._e = [];
	t.ready = function(f) {
		t._e.push(f);
	};

	return t;
	}(document, "script", "twitter-wjs"));</script>
@endpush

resources/views/pages/contact-us.blade.php
@extends('layouts._base')

@push('page-meta')
<title>Contact Us - 123Quanto</title>
@endpush

@push('body-class')
<body id="contact-page">
@endpush

@section('content')
<section id="hero-image" class="hero-image" data-interchange="[{{ asset('assets/img/background-hero-image-download-app-large.jpg') }}, xsmall], [{{ asset('assets/img/background-hero-image-download-app-large.jpg') }}, small], [{{ asset('assets/img/background-hero-image-download-app-large.jpg') }}, medium], [{{ asset('assets/img/background-hero-image-download-app-large.jpg') }}, large]">
	<div class="grid-container">
    	<div class="grid-x grid-padding-x">
	    	<div class="cell xsmall-12 large-6" id="left">
		    	<h1>How can we make our Service better for you?</h1>
		    	
		    	<p>123Quanto understands that our users are the reason we exist.</p> 

				<p>Please help make our service better by offering your valuable feedback. </p>
				
				<p>Thank you from <img src="{{ asset('assets/img/logo-123quanto-white.png') }}" alt="Car for Sale Vancouver"></p>
				
				<ul class="share">
					<li>Tell your friends about us</li>
					
					<li>
                        <a href="https://www.facebook.com/sharer/sharer.php?u={{ urlencode(url('/download-app')) }}" class="socmed-share">
                        	<i class="fa fa-facebook-square fa-2x"></i>
                        </a>
                    </li>

                    <li>
                        <a href="https://twitter.com/home?status=Download%20the%20123Quanto%20app%20today.%20{{ urlencode(url('/download-app')) }}" class="socmed-share">
                        	<i class="fa fa-twitter fa-2x"></i>
                        </a>
                    </li>
				</ul>
	    	</div>
	    	
	    	<form class="cell xsmall-12 xsmall-offset-0 large-5 large-offset-1" id="right">
		    	<div class="grid-x grid-padding-x">
			    	<div class="cell medium-6">
				    	<label>First name
				    		<input type="text" placeholder="Required field">
				    	</label>
			    	</div>
			    	
			    	<div class="cell medium-6">
				    	<label>Last name
				    		<input type="text" placeholder="Required field">
				    	</label>
			    	</div>
		    	</div>
		    	
		    	<div class="grid-x grid-padding-x">
			    	<div class="cell large-12">
				    	<label>Email
				    		<input type="email" placeholder="Required field">
				    	</label>
			    	</div>
		    	</div>
		    	
		    	<div class="grid-x grid-padding-x">
			    	<div class="cell medium-6">
				    	<legend>I am a:</legend>
				    	
				    	<div class="faux-input">
					    	<input type="radio" name="type" id="seller-type">
					    	
					    	<label for="seller-type">Seller</label>
				    	</div>
				    	
				    	<div class="faux-input">
					    	<input type="radio" name="type" id="dealer-type">
					    	
					    	<label for="dealer-type">Dealer</label>
				    	</div>
			    	</div>
			    	
			    	<div class="cell medium-6">
				    	<label>Dealership Name
				    		<input type="text">
				    	</label>
			    	</div>
		    	</div>
		    	
		    	<div class="grid-x grid-padding-x">
			    	<div class="cell large-12">
				    	<label>Message
				    		<textarea placeholder="Required field" rows="5"></textarea>
				    	</label>
			    	</div>
		    	</div>
		    	
		    	<div class="grid-x grid-padding-x">
			    	<div class="cell large-12 text-right">
				    	<button class="cta">Submit</button>
			    	</div>
		    	</div>
	    	</form>
    	</div>
	</div>
</section>
@endsection

@push('page-scripts')
<script>
	//
	var scene1_controller = new ScrollMagic.Controller();
	
	var scene1 = new ScrollMagic.Scene({
		triggerElement: "section#hero-image",
		//triggerHook: "onEnter",
		duration: "100%"
		
	})
	//.addIndicators()
	.on("enter", function(){
		$("section#hero-image").addClass('is-in-view');
	})
	.addTo(scene1_controller);
</script>
@endpush