routes/web.php
<?php

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');


////////////////////////////// ADMIN AREA //////////////////////////////

Route::prefix('/admin')->middleware('auth')->group(function () {

    Route::get('/', function () {
            return redirect()->route('dashboard.index');
    })->name('admin.index');

    Route::view('/dashboard', 'backend.dashboard.index')->name('dashboard.index');

    Route::resource('/category', 'CategoryController');
    Route::resource('/tag', 'TagController');
    Route::resource('/post', 'PostController');
    Route::resource('/like', 'LikeController');
    
    Route::resource('/user', 'UserController');
    
});


////////////////////////////// FRONT-END //////////////////////////////

Route::get('/', 'MainController@home');
Route::get('/how-it-works', 'MainController@how_it_works');
Route::get('/sellers', 'MainController@sellers');
Route::get('/dealers', 'MainController@dealers');
Route::get('/blog', 'MainController@blog');
Route::get('/blog/post/{id}', 'MainController@article')->name('blog.article');
Route::get('/about-us', 'MainController@about_us');
Route::get('/contact-us', 'MainController@contact_us');
Route::get('/download-app', 'MainController@download_app');
Route::get('/faq', 'MainController@faq');
Route::get('/tips', 'MainController@tips');

Route::get('/tag/{tag}', 'MainController@blogsByTag')->name('blogs.by-tag');
Route::get('/category/{category}', 'MainController@blogsByCategory')->name('blogs.by-category');

Route::resource('post-like', 'PostLikeController', ['parameters' => ['post-like' => 'post']]);

//
Route::any('/assets/img/{slug}', function(){
    return \Image::canvas(800, 600, '#ff0000')->response('jpg');
});

app/User.php
<?php

namespace App;

use App\Traits\UuidKey;
use App\Scopes\OrderByNameScope;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use UuidKey;
    use HasRoles;
    use Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'name', 
        'email', 
        'password',
    ];

    protected $hidden = [
        'id', 
        'password', 
        'remember_token',
    ];

    protected $dates = ['deleted_at'];

    /******************************************* SCOPE *******************************************/

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new OrderByNameScope());
    }


    /*************************************** RELATIONSHIP ****************************************/

    /**
     * One-to-Many: A user may create zero or many post
     *
     * This function will retrieve the posts created by a user, if any.
     * See: Post' user() method for the inverse
     *
     * @return mixed
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    /**
     * One-to-Many: A user may create zero or many post's preview
     *
     * This function will retrieve the creator (user) of a post's preview.
     * See: Preview' user() method for the inverse
     *
     * @return mixed
     */
    public function previews()
    {
        return $this->hasMany(Preview::class);
    }

    /**
     * One-to-Many: A user may give zero or many likes (to a post)
     *
     * This function will retrieve the likes given by a user
     * See: Like' user() method for the inverse
     *
     * @return mixed
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\UserStore;
use App\Http\Requests\UserUpdate;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(env('PAGINATE', 5));

        // Use alternative content template
        $content_alt = true;

        return view('backend.user.index',
                    compact(
                        'users',
                        'content_alt'
                    )
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\UserStore  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStore $request)
    {
        User::create($request->all());

        return back()->with('success-message', 'New user has been added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $users     = User::paginate(env('PAGINATE', 5));
        $user_edit = $user;

        // Use alternative content template
        $content_alt = true;

        return view('backend.user.index',
                    compact(
                        'user_edit',
                        'users',
                        'content_alt'
                    )
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UserUpdate  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdate $request, User $user)
    {
        $user->update($request->all());

        return redirect()
                ->route('user.index', [
                    'page' => $request->page ?? 1
                ])
                ->with('success-message', 'User has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return back()->with('success-message', 'User has been removed.');
    }
}

resources/views/backend/user/_form.blade.php
<div class="box-header with-border">

    @if (URL::current() == route('user.index'))

        <h3 class="box-title">Create New User</h3>

    @elseif (URL::current() == route('user.edit', $user_edit))

        <h3 class="box-title">Edit User</h3>

    @endif

</div>

@if (URL::current() == route('user.index'))

    <form action="{{ route('user.store') }}" method="post">

@elseif (URL::current() == route('user.edit', $user_edit))

    <form action="{{ route('user.update', $user_edit) }}" method="post">

        {{ method_field('PATCH') }}

        <input type="hidden" name="page" id="name" value="{{ $_GET['page'] }}">

@endif

        {{ csrf_field() }}

        <div class="box-body">
            <div class="form-group {{ $errors->has('name') ? 'has-error has-feedback' : '' }}">
                <label for="name">
                    Name @include('common.form.label-required-field')
                </label>

                <input type="text" class="form-control" id="name" name="name"
                       value="{{ old('name') ?: (isset($user_edit->name) ? $user_edit->name : '') }}">

                @if ($errors->has('name'))
                    @include('common.form.input-error-message', ['message' => $errors->first('name')])
                @endif
            </div>

            <div class="form-group {{ $errors->has('email') ? 'has-error has-feedback' : '' }}">
                <label for="email">
                    Email @include('common.form.label-required-field')
                </label>

                <input type="text" class="form-control" id="email" name="email"
                       value="{{ old('email') ?: (isset($user_edit->email) ? $user_edit->email : '') }}">

                @if ($errors->has('email'))
                    @include('common.form.input-error-message', ['message' => $errors->first('email')])
                @endif
            </div>

            <div class="form-group {{ $errors->has('password') ? 'has-error has-feedback' : '' }}">
                <label for="password">
                    Password @include('common.form.label-required-field')
                </label>

                <input type="password" class="form-control" id="password" name="password"
                       value="{{ old('password') ?: (isset($user_edit->password) ? $user_edit->password : '') }}">

                @if ($errors->has('password'))
                    @include('common.form.input-error-message', ['message' => $errors->first('password')])
                @endif
            </div>

            <div class="form-group">
                @component('common.form.button-save-new-or-save-changes')
                    @slot('route_create', route('user.index'))
                    @slot('route_edit', route('user.edit', ($user_edit ?? 0)))
                @endcomponent

                @component('common.form.button-cancel')
                    @slot('route_edit', route('user.edit', ($user_edit ?? 0)))
                    @slot('route_redirect', route('user.index', ['page' => $_GET['page'] ?? 1]))
                @endcomponent
            </div>
        </div>
    </form>

resources/views/backend/user/index.blade.php
@extends('backend.layout.master', [
    'left_content_size' => 5,
    'right_content_size' => 3,
])

@section('content-title', 'USER')

@section('content-alt-header', 'User List')

@section('content-alt-body')
    @if ($users->isEmpty())
        @include('common.datalist.no-data')
    @else
        <table id="table1" class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th class="text-center">Name</th>
                    <th class="text-center">Email</th>
                    <th width="100"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                    <tr>
                        <td>
                            <a href="{{ route('user.show', $user) }}">{{ $user->name }}</a>
                        </td>
                        <td>
                            {{ $user->email }}
                        </td>
                        <td class="text-right">
                            @component('common.datalist.button-edit')
                                @slot('text', '')
                                @slot('route', route('user.edit', [
                                                        $user,
                                                        'page' => $_GET['page'] ?? 1
                                                     ]
                                               )
                                )
                            @endcomponent

                            @component('common.datalist.button-remove')
                                @slot('text', '')
                                @slot('route', route('user.destroy', $user))
                            @endcomponent
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="pull-right">
            {{ $users->links() }}
        </div>
    @endif
@endsection

@section('content-alt-form')
    @include('backend.user._form')
@endsection

resources/views/backend/user/show.blade.php
@extends('backend.layout.master')
@section('content-title')
    USER: {{ $user->name }}
@endsection

@section('backend.custom-content')
<div class="content">
    <div class="row">
        <div class="col-md-4">
            @component('backend.layout._box')
                @slot('bodyClass', 'no-padding')
                @slot('title', 'User Detail')
                {{-- @slot('footer', 'User Detail') --}}
                <table class="table table-stripped">
                    <tr>
                        <th>Name</th>
                        <td>{{ $user->name }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td><a href="mailto:{{ $user->email }}">{{ $user->email }}</a></td>
                    </tr>
                </table>

            @endcomponent
        </div>

        <div class="col-md-4">
            @component('backend.layout._box')
                @slot('bodyClass', 'no-padding')
                @slot('title', 'Active Class')
                <table class="table table-stripped">
                    @foreach ($activeProducts as $product)
                    <tr>
                        <td>
                            <strong>{{ $product->name }}</strong> <br>
                            {{ formatDate($product->start_at) }} - {{ formatDate($product->end_at) }}
                            {{ $product->location_name }}
                        </td>
                    </tr>
                    @endforeach
                </table>
            @endcomponent
            @component('backend.layout._box')
                @slot('bodyClass', 'no-padding')
                @slot('title', 'Upcoming Class')
                <table class="table table-stripped">
                    @foreach ($upcomingProducts as $product)
                    <tr>
                        <td>
                            <strong>{{ $product->name }}</strong> <br>
                            {{ formatDate($product->start_at) }} - {{ formatDate($product->end_at) }} <br>
                            {{ $product->location_name }}
                        </td>
                    </tr>
                    @endforeach
                </table>
            @endcomponent
        </div>

        <div class="col-md-4">
            <h4>Order History</h4>
            <ul class="timeline">
                @foreach ($user->orders as $order)
                  <li>
                        <i class="fa fa-file-text-o bg-blue"></i>
                        <div class="timeline-item">
                            <h3 class="timeline-header">{{ formatDate($order->created_at) }}</h3>
                            <div class="timeline-body">
                                @foreach ($order->products as $product)
                                    <p><strong>{{ $product->pivot->name }}</strong> <br>
                                        IDR {{ formatCurrency($product->pivot->price) }} <br>
                                        {{ formatDate($product->pivot->start_at) }} -
                                        {{ formatDate($product->pivot->end_at) }}
                                    </p>
                                @endforeach
                            </div>
                        <div class="timeline-footer">
                        </div>
                    </div>
                </li>
                @endforeach
            </ul>
        </div>
    </div>
</div>
@endsection

@push('footer-scripts')
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
@endpush